version: '3'

services:
  ovsdb-server:
    image: openvswitch/ovs:2.11.2_debian
    command: ovsdb-server
    network_mode: host

  ubuntu1:
    image: ubuntu:latest
    depends_on:
      - ovsdb-server
    command: tail -f /dev/null  # Keeps the container running

  ubuntu2:
    image: ubuntu:latest
    depends_on:
      - ovsdb-server
    command: tail -f /dev/null  # Keeps the container running
