version: '3'

services:
  ovs-switch:
    image: openvswitch/ovs:latest
    privileged: true
    networks:
      - ovs-network

  ubuntu1:
    image: ubuntu:latest
    networks:
      ovs-network:
        aliases:
          - ubuntu1
    command: tail -f /dev/null  # Keeps the container running

  ubuntu2:
    image: ubuntu:latest
    networks:
      ovs-network:
        aliases:
          - ubuntu2
    command: tail -f /dev/null  # Keeps the container running

networks:
  ovs-network:
    external: true
